apiVersion: apps/v1
kind: Deployment

metadata:
  name: dj-orange
  labels:
    name: dj-orange

spec:
  replicas: 3
  selector:
    name: my-dj-app
  template:
    metadata:
      labels:
        name: my-dj-app
    spec:
      containers:
      - name: dj-orange
        image: inforian/dj:orange
        ports:
        - containerPort: 8000
